### PR TITLE
Rewrite 2sectors example, use one file for small examples, combine good type and quantity into one object

### PR DESCRIPTION
**Pull request by rht**
And add `accept_offers` shorthand.

### CODE REVIEW

**Comment by DavoudTaghawiNejad** [comment]
I'd rather prefer to reject this. The shorthand accept_offers is not really useful in real life and I don't think the change to set_cobb_douglas makes it easier.

**Comment by rht** [comment]
Was about to revert `accept_offers`, but I recalled one way to justify it is that it serves a symmetric counterpart to `get_offers`. Additionally, the pattern shows up in 50% of the examples.

The change to `set_cobb_douglas` is also based on the same reason (uniformity): if the output is a dict of {'good_name': quantity, ...}, then the input should be the case as well.

**Comment by DavoudTaghawiNejad** [comment]
rather than introduce accept_offers, we need better examples then.

**Comment by rht** [comment]
Agreed the examples need to be much better/relevant.

**Comment by DavoudTaghawiNejad** [comment]
A cobb-douglas function is x = a*q^beta, where q and beta are vectors and a is a scalar. Therefore beta and q are dictionaries and a is a float.

**Pull request closed without merging**
